"""fecha_cierre

Revision ID: 38a1ff5793ad
Revises: 
Create Date: 2025-04-27 16:44:18.961763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a1ff5793ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asesora', schema=None) as batch_op:
        batch_op.drop_column('temp_permission_expiry')

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_cierre', sa.DateTime(), nullable=True))
        batch_op.drop_column('fecha_finalizacion')
        batch_op.drop_column('fecha_creacion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creacion', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('fecha_finalizacion', sa.DATETIME(), nullable=True))
        batch_op.drop_column('fecha_cierre')

    with op.batch_alter_table('asesora', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_permission_expiry', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
